### ISSUE TITLE
https://cors-anywhere.herokuapp.com/https://api.twitter.com/oauth/access_token 401 (Unauthorized)

### ISSUE THREAD

**Issue by AbdurRahamanAR** [alexandrtovmach/react-twitter-login#7] opened 2019-12-18 13:10 UTC
The response give me this error.

**authCallback function**
```
const responseTwitter = (err, res)=> {
    if(err){
      console.log(err)
    } else {
      console.log(res)
    }
  }
```

**Component**
```
<TwitterLogin
          authCallback={responseTwitter}
          consumerKey={'E6FhsghRQajcWdIWj7lJ0UNIV'}
          consumerSecret={'segz9Q8sqh7rOn3EFUDfauQsoIavjxjrqhfnd1PUOCmzjVKyck'}
          className={'hello'}
          callbackUrl={window.location.href}
          scope="openId email name"
          children={
            <IconButton
              className={classes.item}
              style={{
                marginLeft: 0
              }}
              classes={{root: classes.buttonRoot}}
            >
              <img src={twitterIcon} alt={`login with twitter`}/>
            </IconButton>
} />
```

hear the authCallback response: 
```
{Request token missing: undefined}
Request token missing: undefined
__proto__: Object
```

**Comment by alexandrtovmach** [comment] 2019-12-24 21:29
@AbdurRahamanAR Could you provide with your `window.location.href` to I can reproduce it. My current suggestion is wrong `callbackUrl` that not allowed for provided credentials

**Comment by alexandrtovmach** [comment] 2019-12-24 21:30
Another thing: Why you provide `scope` parameter? There is no API for that in current version, so it'll be ignored

**Comment by alexandrtovmach** [comment] 2019-12-31 13:06
@AbdurRahamanAR ping

**Comment by alexandrtovmach** [comment] 2020-01-06 17:03
Closed as unactive

**Comment by seanaguinaga** [comment] 2020-03-28 00:32
I am having the same issue

Any ideas?

![image](https://user-images.githubusercontent.com/15254340/77810266-e16e0580-7050-11ea-91ff-e4c4905f30df.png)

**Comment by seanaguinaga** [comment] 2020-03-28 00:32
![image](https://user-images.githubusercontent.com/15254340/77810276-ef238b00-7050-11ea-9b35-b281ac7502e4.png)

**Comment by GonzaloCalandria** [comment] 2020-09-04 13:09
I'm having the same problem... how can I fix this?

**Comment by alexandrtovmach** [comment] 2020-09-04 20:31
I'll have more time on next week. Will investigate

**Comment by GonzaloCalandria** [comment] 2020-09-04 20:31
Thank you @alexandrtovmach !!!

**Comment by austinmayer** [comment] 2020-09-16 18:28
+1 on this

**Comment by timurliftiiev** [comment] 2020-09-18 10:46
The same issue, has anybody been able to fix it?

**Comment by dietmarja** [comment] 2020-09-26 12:25
I tried the change a request-token against an access token both with curl and Postman. Same error message: Request token missing

curl --location --request POST 'https://api.twitter.com/oauth/access_token?oauth_token=%20.%20oauth_token=4lKY5wAAAAAA1KlnAAABdMpAhMo&oauth_token_secret=sFgYzHRQgMg1lYesIfTrxieqTC13ChSP&oauth_callback_confirmed=true' \
--header 'Cookie: personalization_id="v1_QHYPF6pC6csNWzFwFIkmlw=="; guest_id=v1%3A159372357452032491; lang=en'

**Comment by neltoby** [comment] 2020-10-01 13:22
i am having same issue as well

**Comment by alienbuild** [comment] 2020-10-04 12:41
+1

**Comment by alexandrtovmach** [comment] 2020-10-05 18:22
@neltoby your issue seems unrelated to this. Could you create another one?

**Comment by alexandrtovmach** [comment] 2020-10-05 18:28
Thanks everyone for reporting and waiting =)
So I'm still not sure what exactly the problem because can't reproduce it, but... I found another interesting problem in another issue #8

Please check [this comment](https://github.com/alexandrtovmach/react-twitter-login/issues/8#issuecomment-703791418) and let me know if this bug reproducing only for described case. If yes, could you also try to update to [v1.2.1](https://www.npmjs.com/package/react-twitter-login/v/1.2.1) and try again.

**Closed** 2021-05-10 15:01 UTC
Labels: question
